### Universal Functions

In [1]:
import numpy as np

In [2]:
a = np.arange(3)
a

array([0, 1, 2])

In [3]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

In [5]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684])

In [6]:
b = np.array([1, 3, 7])
b

array([1, 3, 7])

In [7]:
np.add(a,b)

array([1, 4, 9])

#### Indexing, Slicing and Iterating

In [8]:
a = np.arange(8)**4
a

array([   0,    1,   16,   81,  256,  625, 1296, 2401], dtype=int32)

In [9]:
a[5]

625

In [10]:
a[3:6]

array([ 81, 256, 625], dtype=int32)

In [11]:
a[::-1]

array([2401, 1296,  625,  256,   81,   16,    1,    0], dtype=int32)

In [12]:
def f(x, y):
    return 10*x+y


In [14]:
a = np.fromfunction(f, (3, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [15]:
a[0:5, 1]

array([ 1, 11, 21])

In [16]:
a[:, 1]

array([ 1, 11, 21])

In [17]:
a[1:2, :]

array([[10, 11, 12, 13]])

In [19]:
for data in a.flat:
    print(data)

0
1
2
3
10
11
12
13
20
21
22
23
