In [2]:
import numpy as np

In [7]:
numpy_arr = np.arange(12).reshape(3, 4)
numpy_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
numpy_arr.shape

(3, 4)

In [9]:
numpy_arr.ndim

2

In [14]:
numpy_arr.dtype

dtype('int32')

In [15]:
type(numpy_arr)

numpy.ndarray

In [17]:
a = np.array([3, 4, 7])
a

array([3, 4, 7])

In [18]:
a.ndim

1

In [19]:
a.dtype

dtype('int32')

In [20]:
a.shape

(3,)

In [21]:
b = np.array([(1,2,3), (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b.shape

(2, 3)

In [25]:
b.ndim

2

In [26]:
b.dtype

dtype('int32')

In [27]:
b.size

6

In [30]:
c = np.array([(1, 7), (8, 4)], dtype=complex)
c

array([[1.+0.j, 7.+0.j],
       [8.+0.j, 4.+0.j]])

In [31]:
d = np.array([[1,2], [3,7]], dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 7.+0.j]])

In [33]:
e = np.zeros((5,6))
e

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
e.dtype

dtype('float64')

In [39]:
f = np.ones((8,10), dtype=np.int64)
f

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [41]:
g = np.empty((4,4))
g

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [44]:
np.empty((2,3))

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313],
       [1.48539705e-313, 1.90979621e-313, 2.33419537e-313]])