In [3]:
import numpy as np
from numpy import pi

In [4]:
a = np.linspace(0.5, 1, 8)
a

array([0.5       , 0.57142857, 0.64285714, 0.71428571, 0.78571429,
       0.85714286, 0.92857143, 1.        ])

In [6]:
np.linspace(3, pi, 5)

array([3.        , 3.03539816, 3.07079633, 3.10619449, 3.14159265])

In [12]:
np.sin(90)

0.8939966636005579

In [13]:
b = np.arange(24).reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [16]:
np.arange(30).reshape(5, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [19]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a = np.array([2, 3, 1, 5])
b = np.arange(4)

In [23]:
a-b

array([ 2,  2, -1,  2])

In [24]:
a ** 2

array([ 4,  9,  1, 25], dtype=int32)

In [25]:
np.sin(a)

array([ 0.90929743,  0.14112001,  0.84147098, -0.95892427])

In [26]:
a > 4

array([False, False, False,  True])

In [27]:
a.dot(b)

20

### Maths operation for 2d array

In [40]:
a = np.array([(1,4), (5,1)])
b = np.array([(1,1), (2,1)])

In [41]:
a

array([[1, 4],
       [5, 1]])

In [42]:
b

array([[1, 1],
       [2, 1]])

In [43]:
a.dot(b)

array([[9, 5],
       [7, 6]])

In [44]:
a @ b

array([[9, 5],
       [7, 6]])

In [45]:
b += a

In [46]:
b

array([[2, 5],
       [7, 2]])

In [50]:
a = np.ones(3, dtype=int)
b = np.linspace(2, pi, 3)

In [51]:
a

array([1, 1, 1])

In [52]:
b

array([2.        , 2.57079633, 3.14159265])

In [54]:
a.dtype

dtype('int32')

In [55]:
b.dtype

dtype('float64')

In [56]:
c = a + b

In [57]:
np.exp(0)

1.0

In [58]:
np.exp(c*1j)

array([-0.9899925 +0.14112001j, -0.90929743-0.41614684j,
       -0.54030231-0.84147098j])

In [65]:
a = np.random.random((2, 3))

In [66]:
a

array([[0.79165189, 0.73122125, 0.20383228],
       [0.99544848, 0.70000589, 0.5987051 ]])

In [68]:
a.sum()

4.020864900228506

In [70]:
a.min()

0.203832277209112

In [71]:
a.max()

0.9954484765594778

In [72]:
b = np.arange(12).reshape(3,4)

In [73]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
b.sum(axis=1)

array([ 6, 22, 38])

In [75]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [76]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)