In [1]:
import numpy as np

#### Shape Manipulation

In [3]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 3., 5., 9.],
       [5., 0., 5., 2.],
       [2., 7., 7., 4.]])

In [4]:
a.shape

(3, 4)

In [5]:
a.ndim

2

In [7]:
a.ravel()

array([8., 3., 5., 9., 5., 0., 5., 2., 2., 7., 7., 4.])

In [8]:
a.reshape(6,2)

array([[8., 3.],
       [5., 9.],
       [5., 0.],
       [5., 2.],
       [2., 7.],
       [7., 4.]])

In [9]:
a.T

array([[8., 5., 2.],
       [3., 0., 7.],
       [5., 5., 7.],
       [9., 2., 4.]])

In [10]:
a.T.shape

(4, 3)

In [11]:
a.shape

(3, 4)

In [12]:
a.resize((2,6))
a

array([[8., 3., 5., 9., 5., 0.],
       [5., 2., 2., 7., 7., 4.]])

In [13]:
a.reshape(3,-1)

array([[8., 3., 5., 9.],
       [5., 0., 5., 2.],
       [2., 7., 7., 4.]])

In [14]:
a = np.floor(10*np.random.random((2,2)))
a

array([[3., 2.],
       [2., 9.]])

In [15]:
b = np.floor(10*np.random.random((2,2)))
b

array([[3., 5.],
       [3., 8.]])

In [16]:
np.hstack((a, b))

array([[3., 2., 3., 5.],
       [2., 9., 3., 8.]])

In [17]:
np.vstack((a, b))

array([[3., 2.],
       [2., 9.],
       [3., 5.],
       [3., 8.]])

In [18]:
a = np.floor(10*np.random.random((2,12)))
a

array([[9., 0., 4., 8., 4., 0., 0., 1., 4., 7., 7., 0.],
       [3., 3., 0., 6., 6., 8., 3., 5., 6., 6., 9., 2.]])

In [19]:
np.hsplit(a, 3)

[array([[9., 0., 4., 8.],
        [3., 3., 0., 6.]]),
 array([[4., 0., 0., 1.],
        [6., 8., 3., 5.]]),
 array([[4., 7., 7., 0.],
        [6., 6., 9., 2.]])]

In [20]:
np.hsplit(a, (3,4))

[array([[9., 0., 4.],
        [3., 3., 0.]]),
 array([[8.],
        [6.]]),
 array([[4., 0., 0., 1., 4., 7., 7., 0.],
        [6., 8., 3., 5., 6., 6., 9., 2.]])]